fix: emile does not install dependencies if required

diff --git a/emile b/emile
--- a/emile
+++ b/emile
@@ -1,5 +1,27 @@
 #!/usr/bin/env bash
 
+# check if cli/node_modules exists
+if [ ! -d "cli/node_modules" ]; then
+    echo "CLI dependencies need installed, installing CLI..."
+
+    # run npm install inside cli
+    npm install --prefix cli
+
+    # check if install failed
+    if [ $? -ne 0 ]; then
+        echo "Failed to install dependencies"
+        exit 1
+    fi
+
+    # check if node_modules exists
+    if [ ! -d "cli/node_modules" ]; then
+        echo "Failed to install dependencies"
+        exit 1
+    fi
+
+    echo "Installed CLI"
+fi
+
 # check if cli/dist exists
 if [ ! -d "cli/dist" ]; then
     echo "CLI needs built, building CLI..."
